version: '3.8'

services:
  backend:
    build:
      dockerfile: backend/
    container_name: rf-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  api:
    build:
      dockerfile: ml_block/
    container_name: rf-ml
    ports:
      - "8071:5000"
    networks:
      - app-network

  frontend:
    build: frontend/
    container_name: rf-frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
